### ISSUE TITLE
Hasher stops after a redirect

### ISSUE THREAD

**Issue by FLamparski** [narirou/hasher#3]
Hasher stops routing after a redirect. I suspect this is due to the code at [these lines](https://github.com/narirou/hasher/blob/master/hahser.js#L121-L123) - the arguments to setTimeout are the wrong way round.

**Comment by narirou** [comment]
Hi, @FLamparski 
This is mistake..Thank you for your report and pull-request!

**Comment by FLamparski** [comment]
No problem, glad I could help :smile:
